In [4]:
import numpy as np
import pandas as pd
import sklearn

from sklearn import datasets
iris = datasets.load_iris()
x = iris.data
y = iris.target

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train_scaled,y_train)

y_pred = model.predict(x_test_scaled)

from sklearn.metrics import confusion_matrix,accuracy_score, classification_report, roc_curve, roc_auc_score, precision_score, recall_score, f1_score, precision_recall_curve,
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)
confusion_matrix = confusion_matrix(y_test,y_pred)
print(confusion_matrix)

0.9333333333333333
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]
